version: '3.8'

services:
  consciousness:
    build:
      context: .
      target: base
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=sqlite:///./data/consciousness_dev.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "consciousness.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

  celery:
    build:
      context: .
      target: base
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./data/consciousness_dev.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    command: ["uv", "run", "celery", "worker", "-A", "consciousness.tasks", "--loglevel=info"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
    depends_on:
      - consciousness
    restart: unless-stopped

volumes:
  redis_data:
