"""Initial consciousness schema with dynamic devices

Revision ID: 668a1a58feab
Revises:
Create Date: 2025-06-24 00:06:49.993386

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "668a1a58feab"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("activity_type", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("devices_involved", sa.JSON(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("activity_data", sa.JSON(), nullable=False),
        sa.Column("outcomes", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_activities_duration", "activities", ["duration"], unique=False)
    op.create_index(
        "ix_activities_start_time", "activities", ["start_time"], unique=False
    )
    op.create_index("ix_activities_type", "activities", ["activity_type"], unique=False)
    op.create_table(
        "consciousness_sessions",
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("events_processed", sa.Integer(), nullable=False),
        sa.Column("decisions_made", sa.Integer(), nullable=False),
        sa.Column("learning_updates", sa.Integer(), nullable=False),
        sa.Column("initial_state", sa.JSON(), nullable=False),
        sa.Column("final_state", sa.JSON(), nullable=True),
        sa.Column("performance_metrics", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        "ix_consciousness_sessions_start_time",
        "consciousness_sessions",
        ["start_time"],
        unique=False,
    )
    op.create_index(
        "ix_consciousness_sessions_status",
        "consciousness_sessions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "decisions",
        sa.Column("decision_type", sa.String(length=100), nullable=False),
        sa.Column("context", sa.String(length=255), nullable=False),
        sa.Column("trigger", sa.String(length=255), nullable=False),
        sa.Column("options_considered", sa.JSON(), nullable=False),
        sa.Column("chosen_option", sa.JSON(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("expected_outcome", sa.Text(), nullable=False),
        sa.Column("actual_outcome", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("feedback_score", sa.Float(), nullable=True),
        sa.Column("lessons_learned", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decisions_confidence", "decisions", ["confidence"], unique=False
    )
    op.create_index(
        "ix_decisions_created_at", "decisions", ["created_at"], unique=False
    )
    op.create_index("ix_decisions_success", "decisions", ["success"], unique=False)
    op.create_index("ix_decisions_type", "decisions", ["decision_type"], unique=False)
    op.create_table(
        "emotional_states",
        sa.Column("happiness", sa.Float(), nullable=False),
        sa.Column("worry", sa.Float(), nullable=False),
        sa.Column("boredom", sa.Float(), nullable=False),
        sa.Column("excitement", sa.Float(), nullable=False),
        sa.Column("primary_emotion", sa.String(length=50), nullable=False),
        sa.Column("intensity", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("trigger_event", sa.String(length=255), nullable=True),
        sa.Column("context_data", sa.JSON(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_emotional_states_intensity", "emotional_states", ["intensity"], unique=False
    )
    op.create_index(
        "ix_emotional_states_primary_emotion",
        "emotional_states",
        ["primary_emotion"],
        unique=False,
    )
    op.create_index(
        "ix_emotional_states_timestamp",
        "emotional_states",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_created_at", "events", ["created_at"], unique=False)
    op.create_index("ix_events_processed", "events", ["processed"], unique=False)
    op.create_index("ix_events_severity", "events", ["severity"], unique=False)
    op.create_index(
        "ix_events_type_category", "events", ["event_type", "category"], unique=False
    )
    op.create_table(
        "houses",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("square_footage", sa.Float(), nullable=True),
        sa.Column("num_rooms", sa.Integer(), nullable=True),
        sa.Column("num_floors", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_houses_name", "houses", ["name"], unique=False)
    op.create_table(
        "integration_templates",
        sa.Column("integration_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("brand_keywords", sa.JSON(), nullable=False),
        sa.Column("function_keywords", sa.JSON(), nullable=False),
        sa.Column("model_patterns", sa.JSON(), nullable=False),
        sa.Column("device_classes", sa.JSON(), nullable=False),
        sa.Column("supported_features", sa.JSON(), nullable=False),
        sa.Column("discovery_methods", sa.JSON(), nullable=False),
        sa.Column("requires_hub", sa.Boolean(), nullable=False),
        sa.Column("auth_required", sa.Boolean(), nullable=False),
        sa.Column("auth_methods", sa.JSON(), nullable=False),
        sa.Column("config_fields", sa.JSON(), nullable=False),
        sa.Column("interview_questions", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_name"),
    )
    op.create_index(
        "ix_integration_templates_name",
        "integration_templates",
        ["integration_name"],
        unique=False,
    )
    op.create_index(
        "ix_integration_templates_priority",
        "integration_templates",
        ["priority"],
        unique=False,
    )
    op.create_table(
        "memories",
        sa.Column("memory_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("related_entities", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_memories_created_at", "memories", ["created_at"], unique=False)
    op.create_index("ix_memories_importance", "memories", ["importance"], unique=False)
    op.create_index(
        "ix_memories_last_accessed", "memories", ["last_accessed"], unique=False
    )
    op.create_index(
        "ix_memories_type_category",
        "memories",
        ["memory_type", "category"],
        unique=False,
    )
    op.create_table(
        "experiences",
        sa.Column("memory_id", sa.Integer(), nullable=False),
        sa.Column("emotional_state_id", sa.Integer(), nullable=True),
        sa.Column("experience_type", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=100), nullable=False),
        sa.Column("impact_score", sa.Float(), nullable=False),
        sa.Column("lesson_learned", sa.Text(), nullable=True),
        sa.Column("behavior_change", sa.Text(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["emotional_state_id"],
            ["emotional_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_experiences_created_at", "experiences", ["created_at"], unique=False
    )
    op.create_index(
        "ix_experiences_impact_score", "experiences", ["impact_score"], unique=False
    )
    op.create_index(
        "ix_experiences_type_outcome",
        "experiences",
        ["experience_type", "outcome"],
        unique=False,
    )
    op.create_table(
        "interview_sessions",
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.Column("session_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("conversation_log", sa.JSON(), nullable=False),
        sa.Column("current_phase", sa.String(length=50), nullable=False),
        sa.Column("completed_steps", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_interview_sessions_house_status",
        "interview_sessions",
        ["house_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_interview_sessions_started_at",
        "interview_sessions",
        ["started_at"],
        unique=False,
    )
    op.create_table(
        "people",
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("schedule", sa.JSON(), nullable=False),
        sa.Column("is_present", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_people_house_role", "people", ["house_id", "role"], unique=False
    )
    op.create_index("ix_people_name", "people", ["name"], unique=False)
    op.create_table(
        "rooms",
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("room_type", sa.String(length=100), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("square_footage", sa.Float(), nullable=True),
        sa.Column("ceiling_height", sa.Float(), nullable=True),
        sa.Column("windows", sa.Integer(), nullable=False),
        sa.Column("doors", sa.Integer(), nullable=False),
        sa.Column("preferred_temperature", sa.Float(), nullable=True),
        sa.Column("preferred_humidity", sa.Float(), nullable=True),
        sa.Column("lighting_preferences", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rooms_house_type", "rooms", ["house_id", "room_type"], unique=False
    )
    op.create_index("ix_rooms_name", "rooms", ["name"], unique=False)
    op.create_table(
        "devices",
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=255), nullable=False),
        sa.Column("user_description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("detected_brand", sa.String(length=100), nullable=True),
        sa.Column("detected_model", sa.String(length=255), nullable=True),
        sa.Column("integration_type", sa.String(length=100), nullable=False),
        sa.Column("device_class", sa.String(length=50), nullable=False),
        sa.Column("connection_method", sa.String(length=50), nullable=True),
        sa.Column("requires_hub", sa.Boolean(), nullable=False),
        sa.Column("hub_id", sa.Integer(), nullable=True),
        sa.Column("supported_features", sa.JSON(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("requires_auth", sa.Boolean(), nullable=False),
        sa.Column("auth_method", sa.String(length=50), nullable=True),
        sa.Column("config_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_state", sa.JSON(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discovery_method", sa.String(length=50), nullable=False),
        sa.Column("discovery_confidence", sa.Float(), nullable=False),
        sa.Column("interview_session_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hub_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interview_session_id"],
            ["interview_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_devices_device_class", "devices", ["device_class"], unique=False
    )
    op.create_index(
        "ix_devices_discovery_method", "devices", ["discovery_method"], unique=False
    )
    op.create_index(
        "ix_devices_house_integration",
        "devices",
        ["house_id", "integration_type"],
        unique=False,
    )
    op.create_index("ix_devices_status", "devices", ["status"], unique=False)
    op.create_table(
        "control_actions",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("decision_id", sa.Integer(), nullable=True),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("command", sa.String(length=255), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_control_actions_device_status",
        "control_actions",
        ["device_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_control_actions_executed_at",
        "control_actions",
        ["executed_at"],
        unique=False,
    )
    op.create_index(
        "ix_control_actions_type", "control_actions", ["action_type"], unique=False
    )
    op.create_table(
        "device_candidates",
        sa.Column("interview_session_id", sa.Integer(), nullable=False),
        sa.Column("user_description", sa.Text(), nullable=False),
        sa.Column("extracted_keywords", sa.JSON(), nullable=False),
        sa.Column("detected_brand", sa.String(length=100), nullable=True),
        sa.Column("detected_model", sa.String(length=255), nullable=True),
        sa.Column("detected_function", sa.String(length=100), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("possible_integrations", sa.JSON(), nullable=False),
        sa.Column("recommended_integration", sa.String(length=100), nullable=True),
        sa.Column("auto_discovery_results", sa.JSON(), nullable=False),
        sa.Column("auto_discovery_successful", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_device_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interview_session_id"],
            ["interview_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_device_candidates_confidence",
        "device_candidates",
        ["confidence_score"],
        unique=False,
    )
    op.create_index(
        "ix_device_candidates_session_status",
        "device_candidates",
        ["interview_session_id", "status"],
        unique=False,
    )
    op.create_table(
        "device_entities",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("unique_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("device_class", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("unit_of_measurement", sa.String(length=50), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id"),
    )
    op.create_index(
        "ix_device_entities_device_id", "device_entities", ["device_id"], unique=False
    )
    op.create_index(
        "ix_device_entities_entity_type",
        "device_entities",
        ["entity_type"],
        unique=False,
    )
    op.create_table(
        "sensor_readings",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("sensor_type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.Column("reading_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reading_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sensor_readings_device_time",
        "sensor_readings",
        ["device_id", "reading_time"],
        unique=False,
    )
    op.create_index(
        "ix_sensor_readings_time", "sensor_readings", ["reading_time"], unique=False
    )
    op.create_index(
        "ix_sensor_readings_type_time",
        "sensor_readings",
        ["sensor_type", "reading_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sensor_readings_type_time", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_time", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_device_time", table_name="sensor_readings")
    op.drop_table("sensor_readings")
    op.drop_index("ix_device_entities_entity_type", table_name="device_entities")
    op.drop_index("ix_device_entities_device_id", table_name="device_entities")
    op.drop_table("device_entities")
    op.drop_index("ix_device_candidates_session_status", table_name="device_candidates")
    op.drop_index("ix_device_candidates_confidence", table_name="device_candidates")
    op.drop_table("device_candidates")
    op.drop_index("ix_control_actions_type", table_name="control_actions")
    op.drop_index("ix_control_actions_executed_at", table_name="control_actions")
    op.drop_index("ix_control_actions_device_status", table_name="control_actions")
    op.drop_table("control_actions")
    op.drop_index("ix_devices_status", table_name="devices")
    op.drop_index("ix_devices_house_integration", table_name="devices")
    op.drop_index("ix_devices_discovery_method", table_name="devices")
    op.drop_index("ix_devices_device_class", table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_rooms_name", table_name="rooms")
    op.drop_index("ix_rooms_house_type", table_name="rooms")
    op.drop_table("rooms")
    op.drop_index("ix_people_name", table_name="people")
    op.drop_index("ix_people_house_role", table_name="people")
    op.drop_table("people")
    op.drop_index("ix_interview_sessions_started_at", table_name="interview_sessions")
    op.drop_index("ix_interview_sessions_house_status", table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_index("ix_experiences_type_outcome", table_name="experiences")
    op.drop_index("ix_experiences_impact_score", table_name="experiences")
    op.drop_index("ix_experiences_created_at", table_name="experiences")
    op.drop_table("experiences")
    op.drop_index("ix_memories_type_category", table_name="memories")
    op.drop_index("ix_memories_last_accessed", table_name="memories")
    op.drop_index("ix_memories_importance", table_name="memories")
    op.drop_index("ix_memories_created_at", table_name="memories")
    op.drop_table("memories")
    op.drop_index(
        "ix_integration_templates_priority", table_name="integration_templates"
    )
    op.drop_index("ix_integration_templates_name", table_name="integration_templates")
    op.drop_table("integration_templates")
    op.drop_index("ix_houses_name", table_name="houses")
    op.drop_table("houses")
    op.drop_index("ix_events_type_category", table_name="events")
    op.drop_index("ix_events_severity", table_name="events")
    op.drop_index("ix_events_processed", table_name="events")
    op.drop_index("ix_events_created_at", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_emotional_states_timestamp", table_name="emotional_states")
    op.drop_index("ix_emotional_states_primary_emotion", table_name="emotional_states")
    op.drop_index("ix_emotional_states_intensity", table_name="emotional_states")
    op.drop_table("emotional_states")
    op.drop_index("ix_decisions_type", table_name="decisions")
    op.drop_index("ix_decisions_success", table_name="decisions")
    op.drop_index("ix_decisions_created_at", table_name="decisions")
    op.drop_index("ix_decisions_confidence", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(
        "ix_consciousness_sessions_status", table_name="consciousness_sessions"
    )
    op.drop_index(
        "ix_consciousness_sessions_start_time", table_name="consciousness_sessions"
    )
    op.drop_table("consciousness_sessions")
    op.drop_index("ix_activities_type", table_name="activities")
    op.drop_index("ix_activities_start_time", table_name="activities")
    op.drop_index("ix_activities_duration", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
