database:
  url: "sqlite:///./consciousness_dev.db"
  echo: true
  pool_size: 5

consciousness:
  emotion_update_interval: 60
  memory_retention_days: 30
  learning_rate: 0.1
  debug_mode: true

logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/development.log"

devices:
  discovery_interval: 300
  timeout: 30
  retry_attempts: 3
