database:
  url: "sqlite:///./consciousness.db"
  echo: false
  pool_size: 20

consciousness:
  emotion_update_interval: 300
  memory_retention_days: 365
  learning_rate: 0.01
  debug_mode: false

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/production.log"

devices:
  discovery_interval: 600
  timeout: 60
  retry_attempts: 5
