database:
  url: "sqlite:///:memory:"
  echo: false
  pool_size: 1

consciousness:
  emotion_update_interval: 1
  memory_retention_days: 1
  learning_rate: 1.0
  debug_mode: true

logging:
  level: WARNING
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null

devices:
  discovery_interval: 10
  timeout: 5
  retry_attempts: 1
